@echo off

REM Remove files generated by software in this directory and all subdirectories.
REM Essential release files are kept.

echo Removing "ReadSTEP.log" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0ReadSTEP.log"') do del "%%i" /f /q
echo.

echo Removing "OldVersions" directory...
rd "%~p0OldVersions" /s /q
echo.

echo "%~n0.bat" done.